//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

[RequireComponent(typeof(Camera))]
public class ZoomController2d : Zoom
{
	public override void ChangeZoom (float zoomChange)
	{
	
		if (zoomChange != 0) {

			//modify the zoom of every attached camera
			foreach( Camera c in this.GetComponents<Camera>()){

				c.orthographicSize = Mathf.Clamp (c.orthographicSize + zoomChange, this.zoomFactoMin, this.zoomFactoMax);

			}
		}
	}
}

