//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections;
public static class VectorOperators
{
	public static Vector3 Multiply(Vector3 v1, Vector3 v2){
		return new Vector3(v1.x * v2.x, v1.y * v2.y, v1.z * v2.z);
	}
}
